//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UYE()
        {
            this.ODEME = new HashSet<ODEME>();
        }
    
        public int UyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> Dogum_tarihi { get; set; }
        public string Tel_no { get; set; }
        public System.DateTime Kayit_tarihi { get; set; }
        public string Paket_secimi { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<float> Kilo { get; set; }
        public Nullable<float> GuncelKilo { get; set; }
        public Nullable<float> HedefKilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODEME> ODEME { get; set; }
    }
}
