//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUCUTOLC
    {
        public int UyeID { get; set; }
        public Nullable<double> BasBiceps { get; set; }
        public Nullable<double> GunBiceps { get; set; }
        public Nullable<double> BasGogus { get; set; }
        public Nullable<double> GunGogus { get; set; }
        public Nullable<double> BasBel { get; set; }
        public Nullable<double> GunBel { get; set; }
        public Nullable<double> BasOmuz { get; set; }
        public Nullable<double> GunOmuz { get; set; }
        public Nullable<double> BasBacak { get; set; }
        public Nullable<double> GunBacak { get; set; }
    }
}
